-- ============================================================
-- GESTÃO SAC — INSTALAÇÃO COMPLETA DO ZERO
-- ============================================================
-- Execução em dois passos:
--   1. Seção "PASSO 1" como SYSDBA (cria usuário/schema)
--   2. Seção "PASSO 2" em diante como gestao_sac (cria tabelas e dados)
--
-- Banco: Oracle 19c+ em 192.168.0.98:1521/WINT
--
-- Este arquivo é um snapshot da realidade atual do schema. As migrations
-- numeradas 10+ representam a evolução histórica e já estão refletidas
-- aqui — instalações novas usam só este arquivo.
-- ============================================================


-- ============================================================
-- PASSO 1: CRIAR USUÁRIO/SCHEMA
-- Executar conectado como SYSDBA
-- ============================================================

CREATE USER gestao_sac IDENTIFIED BY senha_gestao
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO gestao_sac;
GRANT CREATE SESSION TO gestao_sac;
GRANT CREATE TABLE TO gestao_sac;
GRANT CREATE SEQUENCE TO gestao_sac;
GRANT CREATE VIEW TO gestao_sac;
GRANT UNLIMITED TABLESPACE TO gestao_sac;

COMMIT;


-- ============================================================
-- PASSO 2: CRIAR TABELAS
-- Executar conectado como gestao_sac
-- ============================================================

-- ----------------------------------------------------------
-- TABELA: usuarios
-- ----------------------------------------------------------
CREATE TABLE usuarios (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    nome        VARCHAR2(200)   NOT NULL,
    email       VARCHAR2(200)   NOT NULL,
    senha_hash  VARCHAR2(255)   NOT NULL,
    papel       VARCHAR2(20)    NOT NULL,
    ativo       NUMBER(1)       DEFAULT 1 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_papel CHECK (papel IN ('OPERADOR', 'GERENTE')),
    CONSTRAINT ck_usuarios_ativo CHECK (ativo IN (0, 1))
);

CREATE INDEX idx_usuarios_email ON usuarios (email);


-- ----------------------------------------------------------
-- TABELA: ocorrencias
-- ----------------------------------------------------------
CREATE TABLE ocorrencias (
    id                          INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,

    -- Nota fiscal
    numero_nota_fiscal          VARCHAR2(50)    NOT NULL,

    -- Snapshot do CEDEP no momento da criação
    id_carregamento             INTEGER,
    data_faturamento            DATE,
    data_saida_carregamento     DATE,
    cliente                     VARCHAR2(200),
    motorista                   VARCHAR2(200),
    vendedor                    VARCHAR2(200),
    transportadora              VARCHAR2(200),
    valor_total                 NUMBER(15, 2),

    -- Classificação da ocorrência
    motivo                      VARCHAR2(50)    NOT NULL,
    tipo_ocorrencia             VARCHAR2(50),
    causa_raiz                  VARCHAR2(50),
    responsavel_tipo            VARCHAR2(50),

    -- Coleta (retorno da mercadoria)
    gera_coleta                 NUMBER(1)       DEFAULT 0 NOT NULL,
    motorista_coleta            VARCHAR2(200),

    -- Textos descritivos
    observacoes                 VARCHAR2(2000),
    motivo_pendencia            VARCHAR2(1000),
    resolucao_final             VARCHAR2(2000),
    detalhes_especificos        CLOB,

    -- Fluxo
    status                      VARCHAR2(30)    DEFAULT 'EM_TRATAMENTO' NOT NULL,

    -- Relacionamentos de usuários
    criado_por_id               INTEGER         NOT NULL,
    atribuido_a_id              INTEGER         NOT NULL,
    aprovado_por_id             INTEGER,
    aprovado_em                 TIMESTAMP,

    -- Auditoria
    created_at                  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    -- Chaves estrangeiras
    CONSTRAINT fk_ocor_criado_por   FOREIGN KEY (criado_por_id)   REFERENCES usuarios(id),
    CONSTRAINT fk_ocor_atribuido    FOREIGN KEY (atribuido_a_id)  REFERENCES usuarios(id),
    CONSTRAINT fk_ocor_aprovado_por FOREIGN KEY (aprovado_por_id) REFERENCES usuarios(id),

    -- Restrições de domínio
    CONSTRAINT ck_ocor_status CHECK (status IN (
        'EM_TRATAMENTO', 'PENDENTE', 'CONCLUIDO', 'FINALIZADO'
    )),
    CONSTRAINT ck_ocor_motivo CHECK (motivo IN (
        'AVARIA', 'INVERSAO_MERCADORIA', 'FALTA_MERCADORIA', 'SOBRA_MERCADORIA',
        'DEVOLUCAO_SOLICITADA', 'PEDIDO_TROCA', 'EXTRAVIO', 'ATRASO_ENTREGA',
        'PEDIDO_DUPLICADO', 'PEDIDO_DESACORDO', 'RAZAO_SOCIAL_DESACORDO', 'OUTRO'
    )),
    CONSTRAINT ck_ocor_tipo CHECK (tipo_ocorrencia IN (
        'DEVOLUCAO_TOTAL', 'DEVOLUCAO_PARCIAL', 'REENVIO', 'REPOSICAO',
        'REPOSICAO_CEDEP', 'REPOSICAO_BONIFICADA'
    )),
    CONSTRAINT ck_ocor_causa CHECK (causa_raiz IN (
        'ERRO_EXPEDICAO', 'ERRO_VENDEDOR', 'ERRO_TRANSPORTADORA', 'ERRO_MOTORISTA',
        'DEFEITO_FABRICA', 'DESISTENCIA_CLIENTE', 'ERRO_CLIENTE', 'FORA_ROTA', 'OUTRO'
    )),
    CONSTRAINT ck_ocor_resp CHECK (responsavel_tipo IN (
        'CEDEP', 'VENDEDOR', 'TRANSPORTADORA', 'MOTORISTA',
        'CLIENTE', 'FABRICANTE', 'NAO_APLICAVEL'
    )),
    CONSTRAINT ck_ocor_gera_coleta CHECK (gera_coleta IN (0, 1)),
    CONSTRAINT ck_ocor_detalhes_json CHECK (detalhes_especificos IS JSON)
);

CREATE INDEX idx_ocor_nota       ON ocorrencias (numero_nota_fiscal);
CREATE INDEX idx_ocor_criado     ON ocorrencias (criado_por_id);
CREATE INDEX idx_ocor_atribuido  ON ocorrencias (atribuido_a_id);
CREATE INDEX idx_ocor_status     ON ocorrencias (status);
CREATE INDEX idx_ocor_tipo       ON ocorrencias (tipo_ocorrencia);
CREATE INDEX idx_ocor_resp_tipo  ON ocorrencias (responsavel_tipo);
CREATE INDEX idx_ocor_created    ON ocorrencias (created_at);


-- ----------------------------------------------------------
-- TABELA: anexos
-- ----------------------------------------------------------
CREATE TABLE anexos (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ocorrencia_id       INTEGER         NOT NULL,
    nome_arquivo        VARCHAR2(255)   NOT NULL,
    caminho_arquivo     VARCHAR2(500)   NOT NULL,
    mime_type           VARCHAR2(100),
    tamanho             INTEGER,
    criado_por_id       INTEGER         NOT NULL,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_anx_ocor     FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencias(id) ON DELETE CASCADE,
    CONSTRAINT fk_anx_usuario  FOREIGN KEY (criado_por_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_anx_ocor ON anexos (ocorrencia_id);


-- ----------------------------------------------------------
-- TABELA: ocorrencia_itens
-- ----------------------------------------------------------
CREATE TABLE ocorrencia_itens (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ocorrencia_id       INTEGER         NOT NULL,
    codprod             VARCHAR2(20),
    descricao_produto   VARCHAR2(200),
    qtd_afetada         NUMBER(15, 3),
    valor_unitario      NUMBER(15, 2),
    valor_total         NUMBER(15, 2),
    item_role           VARCHAR2(30)    DEFAULT 'AFETADO' NOT NULL,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_oitem_ocor FOREIGN KEY (ocorrencia_id)
        REFERENCES ocorrencias(id) ON DELETE CASCADE,
    CONSTRAINT ck_oitem_role CHECK (item_role IN (
        'AFETADO', 'ENVIADO_INCORRETAMENTE', 'ITEM_CORRETO'
    ))
);

CREATE INDEX idx_oitem_ocor ON ocorrencia_itens (ocorrencia_id);


-- ----------------------------------------------------------
-- TABELA: ocorrencia_eventos  (timeline / audit log)
-- ----------------------------------------------------------
CREATE TABLE ocorrencia_eventos (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ocorrencia_id   INTEGER         NOT NULL,
    tipo_evento     VARCHAR2(30)    NOT NULL,
    status_anterior VARCHAR2(30),
    status_novo     VARCHAR2(30),
    comentario      VARCHAR2(2000),
    usuario_id      INTEGER         NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_oevt_ocor FOREIGN KEY (ocorrencia_id)
        REFERENCES ocorrencias(id) ON DELETE CASCADE,
    CONSTRAINT fk_oevt_user FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT ck_oevt_tipo CHECK (tipo_evento IN (
        'CRIADA', 'EDITADA', 'COMENTARIO', 'MUDANCA_STATUS', 'ANEXO_ADICIONADO',
        'ANEXO_REMOVIDO', 'ITEM_ADICIONADO', 'APROVADA', 'REPROVADA',
        'ATRIBUICAO_ALTERADA', 'REABERTA'
    ))
);

CREATE INDEX idx_oevt_ocor ON ocorrencia_eventos (ocorrencia_id, created_at);


-- ============================================================
-- PASSO 3: DADOS INICIAIS
-- Seed do usuário administrador (GERENTE)
-- Senha: admin123  (hash bcrypt gerado pela aplicação no startup)
-- A aplicação recria este seed automaticamente se não existir
-- ============================================================

-- (opcional — a aplicação faz o seed no startup automaticamente)
-- INSERT INTO usuarios (nome, email, senha_hash, papel, ativo)
-- VALUES ('Administrador', 'admin@cedep.com',
--         '$2b$12$...hash_bcrypt_de_admin123...', 'GERENTE', 1);

COMMIT;
