-- Migration 12: Adiciona motivo RAZAO_SOCIAL_DESACORDO
-- Executar como gestao_sac_dev no Oracle (192.168.0.98:1521/WINT)

ALTER TABLE ocorrencias DROP CONSTRAINT ck_ocor_motivo;

ALTER TABLE ocorrencias ADD CONSTRAINT ck_ocor_motivo CHECK (motivo IN (
    'AVARIA', 'INVERSAO_MERCADORIA', 'FALTA_MERCADORIA', 'SOBRA_MERCADORIA',
    'DEVOLUCAO_SOLICITADA', 'PEDIDO_TROCA', 'EXTRAVIO', 'ATRASO_ENTREGA',
    'PEDIDO_DUPLICADO', 'PEDIDO_DESACORDO', 'RAZAO_SOCIAL_DESACORDO', 'OUTRO'
));

COMMIT;
